export default {
  actions: { back: '返回', editStep: '編輯 → 步驟 {step}', nextToStep: '下一步：{step}', submitRegistration: '提交報名', backToHome: '返回首頁' },
  wizard: { steps: { attendee: '報名者資料', sessions: '議程', addons: '加購項目', review: '確認資料' } },
  attendee: { selectTicketType: '選擇票種', information: '報名者資料', selected: '✓ 已選擇', ticketAria: '{name} 票券，{price}', fields: { fullName: { label: '姓名', placeholder: '請輸入姓名' }, email: { label: '電子郵件', placeholder: '請輸入電子郵件地址' }, phone: { label: '電話', placeholder: '請輸入電話號碼' }, company: { label: '公司', placeholder: '請輸入公司名稱' }, jobTitle: { label: '職稱', placeholder: '請輸入職稱' }, shippingAddress: { label: '寄送地址', optionalLabel: '寄送地址（選填）', placeholder: '請輸入寄送地址' } } },
  sessions: { heading: '選擇議程', datesAria: '議程日期', countOne: '已選擇 {count} 場議程', countOther: '已選擇 {count} 場議程', empty: '目前沒有可選擇的議程。', soldOut: '已售完', spotLeftOne: '剩餘 {count} 個名額', spotLeftOther: '剩餘 {count} 個名額', selectAria: '{action} {title}。{capacity}。', capacityAria: '{capacity}，已使用 {percent}% 名額', select: '選擇', deselect: '取消選擇' },
  addons: { heading: '選擇加購項目', categoriesAria: '加購項目類別', empty: '此類別目前沒有可選購的項目。', shippingTitle: '寄送資訊', shippingMessage: '周邊商品將於活動前一週寄送至您的地址，請確認步驟 1 的寄送地址正確。', soldOut: '已售完', spotRemainingOne: '剩餘 {count} 個名額', spotRemainingOther: '剩餘 {count} 個名額', conflictSelected: '與已選擇的議程衝突。請取消選擇此工作坊以繼續。', conflictUnavailable: '無法選擇 — 與已選擇的議程衝突。', select: '選擇', deselect: '取消選擇', selectAria: '{action} {name}。{status}', size: '尺寸：', selectSize: '選擇', sizeAria: '{name} 尺寸', selectSizeAria: '選擇 {name} 的尺寸', added: '✓ 已加入訂單', quantity: '數量：', quantityAria: '{name} 數量', decreaseQuantity: '減少 {name} 數量', increaseQuantity: '增加 {name} 數量', max: '上限 {max}', categories: { workshop: '工作坊', meal: '餐飲套組', merchandise: '周邊商品' } },
  review: { title: '確認報名資料', attendee: '報名者資料', sessions: '已選擇的議程', addons: '加購項目', pricing: '價格摘要', grandTotal: '總計', noSessions: '尚未選擇議程。', noAddons: '尚未選擇加購項目。', fixErrors: '提交前請修正下列錯誤', stepError: '步驟 {step}：{message}', fields: { fullName: '姓名', email: '電子郵件', phone: '電話', company: '公司', jobTitle: '職稱', shippingAddress: '寄送地址', ticketType: '票種' }, required: '—（必填）', requiredForMerchandise: '—（購買周邊商品時必填）', empty: '—' },
  summary: { title: '訂單摘要', total: '總計', empty: '尚未選擇項目。', ticket: '{name} 票券', merchandise: '{name} × {quantity}', workshopDiscount: '工作坊折扣（VIP 10%）' },
  success: { title: '報名完成！', confirmation: '確認編號 #{id}', message: '感謝您，{name}！您已成功報名 {event} 的 {ticket} 票券。', email: '確認信將寄送至 {email}。' },
  validation: { 'attendee.fullName.required': '必須填寫姓名。', 'attendee.email.required': '必須填寫電子郵件。', 'attendee.email.invalid': '請輸入有效的電子郵件地址。', 'attendee.phone.required': '必須填寫電話。', 'attendee.phone.invalid': '請輸入含 7 至 15 位數字的有效電話。', 'attendee.company.required': '必須填寫公司名稱。', 'attendee.jobTitle.required': '必須填寫職稱。', 'attendee.shippingAddress.required': '選擇周邊商品時必須填寫寄送地址。', 'ticket.required': '請選擇票種。', 'ticket.invalid': '所選票種目前無法使用。', 'session.invalid': '所選議程目前無法使用。', 'session.soldOut': '所選議程已售完。', 'session.conflict': '所選議程的時間重疊。', 'addon.invalid': '所選加購項目目前無法使用。', 'addon.quantity.invalid': '所選加購項目的數量無效。', 'addon.soldOut': '所選工作坊已售完。', 'addon.workshopConflict': '所選工作坊與已選議程時間重疊。', 'addon.size.required': '請為此周邊商品選擇可用尺寸。' },
}
